name: juck Lint
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache: false
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
